#!/bin/bash

readonly OLD_IFS="$IFS"
readonly PLUGIN_FOLDER="$(dirname $0)"
readonly NO_CORE="$1"

if [ -n "$BOB_PLUGINS" ]; then
    IFS=','
else
    BOB_PLUGINS=$(ls -d $PLUGIN_FOLDER/*/ | sed 's~^'"$PLUGIN_FOLDER"'/~~;s~/$~~')
fi
for plugin in $BOB_PLUGINS; do
    IFS="$OLD_IFS"
    if ! [ -d "$PLUGIN_FOLDER/$plugin" ]; then
        >&2 echo "Ignoring '$plugin' because it's not a client plugin"
        continue
    fi
    if [ -n "$NO_CORE" ] && [[ $plugin == core ]]; then
        continue
    fi
    echo "$plugin"
done
