# This ignore file is used only when building the frontend-flask container.

# Hide everything.
*

# Except for server and api.
!frontend/server
!frontend/api
!.pylintrc
!.pycodestyle
!common/python
!common/vendor
