"""Common geographic function for the frontend server."""


# All departements we want to consider in our app.
# TODO(guillaume): Find a better way to get the departements that are compatible
# E.G. (69M) should not be here, but 2A should.
_ALL_DEPARTEMENTS = {
    '01': 'Ain',
    '02': 'Aisne',
    '03': 'Allier',
    '04': 'Alpes-de-Haute-Provence',
    '05': 'Hautes-Alpes',
    '06': 'Alpes-Maritimes',
    '07': 'Ardèche',
    '08': 'Ardennes',
    '09': 'Ariège',
    '10': 'Aube',
    '11': 'Aude',
    '12': 'Aveyron',
    '13': 'Bouches-du-Rhône',
    '14': 'Calvados',
    '15': 'Cantal',
    '16': 'Charente',
    '17': 'Charente-Maritime',
    '18': 'Cher',
    '19': 'Corrèze',
    '21': 'Côte-dOr',
    '22': 'Côtes-dArmor',
    '23': 'Creuse',
    '24': 'Dordogne',
    '25': 'Doubs',
    '26': 'Drôme',
    '27': 'Eure',
    '28': 'Eure-et-Loir',
    '29': 'Finistère',
    '2A': 'Corse-du-Sud',
    '2B': 'Haute-Corse',
    '30': 'Gard',
    '31': 'Haute-Garonne',
    '32': 'Gers',
    '33': 'Gironde',
    '34': 'Hérault',
    '35': 'Ille-et-Vilaine',
    '36': 'Indre',
    '37': 'Indre-et-Loire',
    '38': 'Isère',
    '39': 'Jura',
    '40': 'Landes',
    '41': 'Loir-et-Cher',
    '42': 'Loire',
    '43': 'Haute-Loire',
    '44': 'Loire-Atlantique',
    '45': 'Loiret',
    '46': 'Lot',
    '47': 'Lot-et-Garonne',
    '48': 'Lozère',
    '49': 'Maine-et-Loire',
    '50': 'Manche',
    '51': 'Marne',
    '52': 'Haute-Marne',
    '53': 'Mayenne',
    '54': 'Meurthe-et-Moselle',
    '55': 'Meuse',
    '56': 'Morbihan',
    '57': 'Moselle',
    '58': 'Nièvre',
    '59': 'Nord',
    '60': 'Oise',
    '61': 'Orne',
    '62': 'Pas-de-Calais',
    '63': 'Puy-de-Dôme',
    '64': 'Pyrénées-Atlantiques',
    '65': 'Hautes-Pyrénées',
    '66': 'Pyrénées-Orientales',
    '67': 'Bas-Rhin',
    '68': 'Haut-Rhin',
    '69': 'Rhône',
    '70': 'Haute-Saône',
    '71': 'Saône-et-Loire',
    '72': 'Sarthe',
    '73': 'Savoie',
    '74': 'Haute-Savoie',
    '75': 'Paris',
    '76': 'Seine-Maritime',
    '77': 'Seine-et-Marne',
    '78': 'Yvelines',
    '79': 'Deux-Sèvres',
    '80': 'Somme',
    '81': 'Tarn',
    '82': 'Tarn-et-Garonne',
    '83': 'Var',
    '84': 'Vaucluse',
    '85': 'Vendée',
    '86': 'Vienne',
    '87': 'Haute-Vienne',
    '88': 'Vosges',
    '89': 'Yonne',
    '90': 'Territoire de Belfort',
    '91': 'Essonne',
    '92': 'Hauts-de-Seine',
    '93': 'Seine-Saint-Denis',
    '94': 'Val-de-Marne',
    '95': "Val-d'Oise",
    '971': 'Guadeloupe',
    '972': 'Martinique',
    '973': 'Guyane',
    '974': 'La Réunion',
    '976': 'Mayotte',
}

# TODO(guillaume): Put those tables in Mongo.
_DEPARTEMENTS_PREFIX = {
    '01': "dans l'",
    '02': "dans l'",
    '03': "dans l'",
    '04': 'dans les ',
    '05': 'dans les ',
    '06': 'dans les ',
    '07': 'en ',
    '08': 'dans les ',
    '09': 'en',
    '10': "dans l'",
    '11': "dans l'",
    '12': "dans l'",
    '13': 'dans les ',
    '14': 'dans le ',
    '15': 'dans le ',
    '16': 'en ',
    '17': 'en ',
    '18': 'dans le ',
    '19': 'en ',
    '2A': 'en ',
    '2B': 'en ',
    '21': 'en ',
    '22': 'en ',
    '23': 'dans la ',
    '24': 'en ',
    '25': 'dans le ',
    '26': 'dans la ',
    '27': "dans l'",
    '28': "dans l'",
    '29': 'dans le ',
    '30': 'dans le ',
    '31': 'en ',
    '32': 'dans le ',
    '33': 'en ',
    '34': "dans l'",
    '35': 'en ',
    '36': "dans l'",
    '37': 'en ',
    '38': 'en ',
    '39': 'dans le ',
    '40': 'dans les ',
    '41': 'dans le ',
    '42': 'dans le ',
    '43': 'en ',
    '44': 'en ',
    '45': 'dans le ',
    '46': 'dans le ',
    '47': 'dans le ',
    '48': 'en ',
    '49': 'dans le ',
    '50': 'dans la ',
    '51': 'dans la ',
    '52': 'en ',
    '53': 'à ',
    '54': 'en ',
    '55': 'en ',
    '56': 'dans le ',
    '57': 'en ',
    '58': 'dans la ',
    '59': 'dans le ',
    '60': "dans l'",
    '61': "dans l'",
    '62': 'dans le ',
    '63': 'dans le ',
    '64': 'dans les ',
    '65': 'dans les ',
    '66': 'dans les ',
    '67': 'dans le ',
    '68': 'en ',
    '69': 'dans le ',
    '70': 'en ',
    '71': 'en ',
    '72': 'en ',
    '73': 'en ',
    '74': 'en ',
    '75': 'à ',
    '76': 'en ',
    '77': 'en ',
    '78': 'dans les ',
    '79': 'aux ',
    '80': 'dans la ',
    '81': 'dans le ',
    '82': 'dans le ',
    '83': 'dans le ',
    '84': 'dans le ',
    '85': 'en ',
    '86': 'dans la ',
    '87': 'en ',
    '88': 'dans les ',
    '89': "dans l'",
    '90': 'dans le ',
    '91': 'en ',
    '92': 'dans les ',
    '93': 'en ',
    '94': 'dans le ',
    '95': 'dans le ',
    '971': 'en ',
    '972': 'en ',
    '973': 'en ',
    '974': 'à la ',
    '976': 'à ',
}


def list_all_departements():
    """List all French département IDs."""
    return _ALL_DEPARTEMENTS.keys()


def get_departement_name(departement_id):
    """Get a departement name."""
    return _ALL_DEPARTEMENTS[departement_id]


def get_in_a_departement_text(departement_id):
    """Compute the French text for "in the Departement" for the given ID."""
    departement_name = get_departement_name(departement_id)
    if departement_name.startswith('La '):
        departement_name = departement_name[len('La '):]
    return _DEPARTEMENTS_PREFIX[departement_id] + departement_name
