// @generated by protoc-gen-json-ts.py.  Do not edit!

declare namespace bayes {

  namespace bob {

    namespace test {

      interface Simple {
        readonly name?: string
        readonly multipleWords?: string
      }

      interface Different {
        readonly name?: string
      }

      interface Timely {
        readonly createdAt?: string
        readonly modifiedAt?: string[]
      }

    }

  }

}
