# Bash functions that makes it easier to use the command line to interface with
# Bob frontend.

BOB_ROOT_FOLDER="$(realpath $(dirname "${BASH_SOURCE[0]}")/../..)"

function _ecs_var_from_json {
  local container=$1
  local var=$2
  shift 2
  jq -r ".taskDefinition.containerDefinitions[] | select(.name == \"$container\") | .environment[] | select(.name ==\"$var\") | .value" "$@"
}

# Access a production environment var of Bob.
#
# You need to have awscli and jq installed, as well have read access to the
# prod configuration.
function bob_prod_var {
  aws ecs describe-task-definition --task-definition=frontend-flask | _ecs_var_from_json flask "$@"
}

# Access a demo environment var of Bob.
#
# You need to have ssh access to the demo server.
function bob_demo_var {
  ssh demo-mygameplan.bayes.org 'bash --login -c "echo \$'$1'"'
}

# Access multiple production environment vars of Bob for a local docker run.
#
# You need to have awscli and jq installed, as well have read access to the
# prod configuration.
function bob_prod_vars {
  tmpfile=$(mktemp)
  aws ecs describe-task-definition --task-definition=frontend-flask > $tmpfile
  for var in "$@"; do
    value="$(_ecs_var_from_json flask "$var" "$tmpfile")"
    echo -n "-e $var=$value "
  done
  # Finalize the line with a linebreak to conform to unix standards.
  echo
  rm "$tmpfile"
}

function bob_importer_var {
  aws ecs describe-task-definition --task-definition=data-importer | _ecs_var_from_json master "$@"
}

function mailjet_template {
  # TODO(cyrille): Deal with `grep -P` issue on MacOS.
  "$BOB_ROOT_FOLDER/frontend/server/asynchronous/mail/templates/mailjet.sh" "$@"
}

function _mailjet_template {
  local cur=${COMP_WORDS[COMP_CWORD]}
  if [ $COMP_CWORD == 1 ]; then
    COMPREPLY=( $(compgen -W "upload download" -- $cur) )
    return
  fi
  templates=$(jq -rc .[].name "$BOB_ROOT_FOLDER/frontend/server/asynchronous/mail/templates/mailjet.json")
  COMPREPLY=( $(compgen -W "$templates" -- $cur))
}

complete -F _mailjet_template mailjet_template
